import type { Metadata } from 'next'
import { Red_Hat_Text } from 'next/font/google'
import './globals.css'

const rht = Red_Hat_Text({ subsets: ['latin'], weight: ['400', '600', '700'] })

export const metadata: Metadata = {
  title: 'Create E-commerce App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={rht.className}>{children}</body>
    </html>
  )
}
